name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build Counselors Lambda Function
      run: GOOS=linux go build -o counselors aws/lambdas/counselors.go      
      
    - name: counselors zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -jrm counselors.zip counselors
    - name: counselors lambda function deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: counselors
        zip_file: counselors.zip

    - name: Build User Post Signup Trigger Lambda Function
      run: GOOS=linux go build -o user_post_signup aws/auth/post_signup/user_post_signup.go    
        
    - name: user post signup trigger zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -jrm user_post_signup.zip user_post_signup
    - name: post signup trigger lambda function deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: user_post_signup
        zip_file: user_post_signup.zip
    
    - name: Build User Login Trigger Lambda Function
      run: GOOS=linux go build -o user_auth aws/auth/login/user_auth.go    
          
    - name: user auth zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -jrm user_auth.zip user_auth
    - name: user auth trigger lambda function deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: user_auth
        zip_file: user_auth.zip

    - name: Build User Pre Signup Trigger Lambda Function
      run: GOOS=linux go build -o user_pre_signup aws/auth/pre_signup/user_pre_signup.go    
            
    - name: user pre signup zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -jrm user_pre_signup.zip user_pre_signup
    - name: user pre signup trigger lambds function deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: user_pre_signup
        zip_file: user_pre_signup.zip
  